pipeline {
    agent any
    stages {
        stage('build') {
            steps {
              sh '''
                 cd ./level-service
                 ./mvnw -DskipTests clean compile
              '''
            }
        }
        stage('test') {
            steps {
              sh '''
                 cd level-service
                     ./mvnw test
              '''
            }
        }
        stage('deliver') {
            steps {
              sh '''
                 cd level-service
                     ./mvnw -DskipTests install
              '''
            }
        }
    }
